### ISSUE TITLE
 Error: Undefined class constant 'MYSQL_ATTR_INIT_COMMAND'

### ISSUE THREAD

**Issue by mrjones-plip** [Packet-Clearing-House/tableManager#18]
when running ``php -S localhost:8000`` in examples and then browsing an example page I get this error:

```
[Wed Mar 27 14:07:16 2019] PHP Fatal error:  Uncaught Error: Undefined class constant 'MYSQL_ATTR_INIT_COMMAND' in /home/mrjones/Documents/tableManager/tableManager.php:763
Stack trace:
#0 /home/mrjones/Documents/tableManager/tableManager.php(71): tableManager->getDbHandle('tableManagerSam...')
#1 /home/mrjones/Documents/tableManager/examples/list_rows_with_links.php(15): tableManager->__construct('192.168.68.42', 'root', '', 'tableManagerSam...', 'people')
#2 {main}
  thrown in /home/mrjones/Documents/tableManager/tableManager.php on line 763
```

**Comment by mrjones-plip** [comment]
while technically a bug, this is because the ``php-mysql`` package isn't installed.  For example, to fix this on on ubuntu I ran ``sudo apt-get install php-mysql``
